name: publish
on: 
  workflow_dispatch:
    inputs:
      increment:
        description: Increment
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
jobs:
  build-test-lint:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: build-test-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: update version
        run: |
          npm version ${{ inputs.increment }}
          git push origin master
      
      - name: read version
        id: read-version
        run: |
          version=$(cat ./package.json | jq '.version' | sed 's/"//g')
          echo "nextVersion=$version" >> "$GITHUB_OUTPUT"
        
      - name: create release
        env:
          VERSION: ${{ steps.read-version.outputs.nextVersion }}
        run: gh release create $VERSION --fail-on-no-commits --generate-notes -t 'Release $VERSION'
      - name: publish extension
        env: 
          VERSION: ${{ steps.read-version.outputs.nextVersion }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npm deploy
