name: publish
on: 
  workflow_dispatch:
    inputs:
      increment:
        description: Increment
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
jobs:
  build-test-lint:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: build-test-lint
    runs-on: ubuntu-latest
    outputs:
      nextVersion: ${{ steps.bump.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: update version
        id: bumb
        run: ehco updating to version ${{ inputs.increment }}
      - name: read version
        run: |
          version=$(echo ./package.json | jq '.version' | sed 's/"//g')
          
      - name: create release
        run: echo release ${{ outputs.nextVersion }}
