name: publish
on: 
  workflow_dispatch:
    inputs:
      increment:
        description: Increment
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
jobs:
  build-test-lint:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: build-test-lint
    runs-on: ubuntu-latest
    steps:
      - name: One
        run: echo ${{ inputs.increment }}
  
