name: publish
on: 
  workflow_dispatch:
    inputs:
      increment:
        description: Increment
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
jobs:
  build-test-lint:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: build-test-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: update version
        id: bumb
        run: echo updating to version ${{ inputs.increment }}
      - name: read version
        run: |
          version=$(cat ./package.json | jq '.version' | sed 's/"//g')
          echo next version is this $version
          echo "nextVersion=$version" >> $GITHUB_OUTPUT
        
      - name: create release
        env:
          VERSION: ${{ steps.bump.outputs.nextVersion }}
        run: echo release $VERSION ${{ steps.bumb.outputs.nextVersion }}
