name: publish
on: 
  workflow_dispatch:
    inputs:
      increment:
        description: Increment
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major
jobs:
  check-branch:
    runs-on: ubuntu-latest
    if: ${{ github.ref === 'refs/heads/master' }}
  build-test-lint:
    needs: check-branch
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: [check-branch, build-test-lint]
    runs-on: ubuntu-latest
    steps:
      - name: One
        run: echo ${{ inputs.increment }}
  
