name: build and test
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'
  merge_group:
    types: [checks_requested]
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: create out directory
        run: mkdir -p ./out/test/
      - name: copy fixtures
        run: npm run copy-fixtures
      - name: run test
        run: |
          export TZ='Europe/Helsinki'
          xvfb-run -a npm test
