name: run tests
on: 
  - pull_request:
    branches: '**'
  - push:
    branches: main
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: run test
        run: xvfb-run -a run tests
