name: run tests
on: pull_request
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: create out directory
        run: mkdir -p ./out/test/
      - name: copy fixtures
        run: npm run copy-fixtures
      - name: set tz helsinki
        run: | 
          date
          
      - name: run test
        run: xvfb-run -a npm test
