name: build and test
on:
  workflow_call:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'
  merge_group:
    types: [checks_requested]
jobs: 
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] #ubuntu-latest, macos-latest, just test windows for now
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: create out directory
        run: mkdir -p ./out/test/
      - name: copy fixtures
        run: npm run copy-fixtures
      - name: check W
        if: runner.os == 'Windows'
        run: | 
          dir out\test\fixtures
          cd
          echo "test"
          pwd
      - name: compile, lint and test
        if: runner.os == 'Linux'
        run: |
          export TZ='Europe/Helsinki'
          xvfb-run -a npm test
      - name: compile, lint and test
        if: runner.os == 'macOS'
        run: |
          export TZ='Europe/Helsinki'
          npm test
      - name: compile, lint, and test
        if: runner.os == 'Windows'
        run: |
          tzutil /s 'FLE Standard Time'
          npm test
